export type Language = 'en' | 'tr';

export const translations = {
  en: {
    auth: {
      login: 'Login',
      register: 'Register',
      username: 'Username',
      password: 'Password',
      phone: 'Phone Number',
      welcomeTitle: 'Welcome to OZBA',
      welcomeDescription: 'Connect with friends and communities through voice chat channels. Create your own servers, join voice rooms, and start talking!',
      setup2FA: 'Setup Two-Factor Authentication',
      disable2FA: 'Disable Two-Factor Authentication',
      verify2FA: 'Enter 2FA Code',
      verify2FADescription: 'Enter the 6-digit code from your authenticator app',
      logout: 'Logout',
    },
    home: {
      welcome: 'Welcome',
      selectServer: 'Select a server to get started',
    },
    server: {
      channels: 'Channels',
      textChannels: 'TEXT CHANNELS',
      voiceChannels: 'VOICE CHANNELS',
      createServer: 'Create a new server',
      serverName: 'Server Name',
      createChannel: 'Create a new channel',
      channelName: 'Channel Name',
      voiceChannel: 'Voice Channel',
      members: 'Members',
      join: 'Join',
      leave: 'Leave',
      invite: 'Invite Friends',
      generateInvite: 'Generate Invite Link',
      mute: 'Mute',
      unmute: 'Unmute',
      kick: 'Kick User',
      ban: 'Ban User',
      makeAdmin: 'Make Admin',
      removeAdmin: 'Remove Admin',
      volume: 'Volume',
    },
    settings: {
      title: 'Settings',
      language: 'Language',
      security: 'Security',
      profile: 'Profile',
      audio: {
        title: 'Audio Settings',
        inputDevice: 'Input Device',
        outputDevice: 'Output Device',
        inputVolume: 'Input Volume',
        outputVolume: 'Output Volume',
        test: 'Test Audio',
      },
    },
    profile: {
      title: 'Profile Settings',
      avatarUrl: 'Avatar URL',
      bio: 'About Me',
      age: 'Age',
      saveChanges: 'Save Changes',
      updateSuccess: 'Success',
      profileUpdated: 'Your profile has been updated',
      updateError: 'Update Failed',
      viewProfile: 'View Profile',
      nickname: 'Nickname',
      status: 'Status',
      statusPlaceholder: 'What are you up to?',
      socialLinks: 'Social Links',
      discord: 'Discord',
      twitter: 'Twitter',
      instagram: 'Instagram',
      website: 'Website',
      privacy: 'Privacy Settings',
      privateProfile: 'Private Profile',
      showLastSeen: 'Show Last Seen',
    },
    chat: {
      welcome: 'Welcome to',
      messagePlaceholder: 'Message',
      send: 'Send',
      addReaction: 'Add Reaction',
      removeReaction: 'Remove Reaction',
      reactions: 'Reactions',
      reactionAdded: 'Reaction added',
      reactionRemoved: 'Reaction removed',
    }
  },
  tr: {
    auth: {
      login: 'Giriş Yap',
      register: 'Kayıt Ol',
      username: 'Kullanıcı Adı',
      password: 'Şifre',
      phone: 'Telefon Numarası',
      welcomeTitle: 'OZBA\'ya Hoş Geldiniz',
      welcomeDescription: 'Sesli sohbet kanalları aracılığıyla arkadaşlarınız ve topluluklarla bağlantı kurun. Kendi sunucularınızı oluşturun, sesli odalara katılın ve sohbete başlayın!',
      setup2FA: 'İki Faktörlü Doğrulamayı Etkinleştir',
      disable2FA: 'İki Faktörlü Doğrulamayı Devre Dışı Bırak',
      verify2FA: '2FA Kodunu Girin',
      verify2FADescription: 'Doğrulayıcı uygulamanızdan 6 haneli kodu girin',
      logout: 'Çıkış Yap',
    },
    home: {
      welcome: 'Hoş Geldiniz',
      selectServer: 'Başlamak için bir sunucu seçin',
    },
    server: {
      channels: 'Kanallar',
      textChannels: 'METİN KANALLARI',
      voiceChannels: 'SESLİ KANALLAR',
      createServer: 'Yeni sunucu oluştur',
      serverName: 'Sunucu Adı',
      createChannel: 'Yeni kanal oluştur',
      channelName: 'Kanal Adı',
      voiceChannel: 'Sesli Kanal',
      members: 'Üyeler',
      join: 'Katıl',
      leave: 'Ayrıl',
      invite: 'Arkadaşlarını Davet Et',
      generateInvite: 'Davet Linki Oluştur',
      mute: 'Sustur',
      unmute: 'Susturmayı Kaldır',
      kick: 'Kullanıcıyı At',
      ban: 'Kullanıcıyı Yasakla',
      makeAdmin: 'Admin Yap',
      removeAdmin: 'Admin Yetkisini Kaldır',
      volume: 'Ses Seviyesi',
    },
    settings: {
      title: 'Ayarlar',
      language: 'Dil',
      security: 'Güvenlik',
      profile: 'Profil',
      audio: {
        title: 'Ses Ayarları',
        inputDevice: 'Giriş Cihazı',
        outputDevice: 'Çıkış Cihazı',
        inputVolume: 'Giriş Ses Seviyesi',
        outputVolume: 'Çıkış Ses Seviyesi',
        test: 'Ses Testi',
      },
    },
    profile: {
      title: 'Profil Ayarları',
      avatarUrl: 'Profil Fotoğrafı URL',
      bio: 'Hakkımda',
      age: 'Yaş',
      saveChanges: 'Değişiklikleri Kaydet',
      updateSuccess: 'Başarılı',
      profileUpdated: 'Profiliniz güncellendi',
      updateError: 'Güncelleme Başarısız',
      viewProfile: 'Profili Görüntüle',
      nickname: 'Takma Ad',
      status: 'Durum',
      statusPlaceholder: 'Ne yapıyorsun?',
      socialLinks: 'Sosyal Medya Bağlantıları',
      discord: 'Discord',
      twitter: 'Twitter',
      instagram: 'Instagram',
      website: 'Web Sitesi',
      privacy: 'Gizlilik Ayarları',
      privateProfile: 'Özel Profil',
      showLastSeen: 'Son Görülme Göster',
    },
    chat: {
      welcome: 'Hoş geldiniz',
      messagePlaceholder: 'Mesaj',
      send: 'Gönder',
      addReaction: 'Tepki Ekle',
      removeReaction: 'Tepkiyi Kaldır',
      reactions: 'Tepkiler',
      reactionAdded: 'Tepki eklendi',
      reactionRemoved: 'Tepki kaldırıldı',
    }
  }
};