export type Language = 'en' | 'tr';

export const translations = {
  en: {
    auth: {
      login: 'Login',
      register: 'Register',
      username: 'Username',
      password: 'Password',
      phone: 'Phone Number',
      welcomeTitle: 'Welcome to OZBA',
      welcomeDescription: 'Connect with friends and communities through voice chat channels. Create your own servers, join voice rooms, and start talking!',
      logout: 'Logout',
      loginSuccess: 'Successfully logged in',
      errors: {
        usernameRequired: 'Username is required',
        usernameTooShort: 'Username must be at least 3 characters',
        passwordRequired: 'Password is required',
        passwordTooShort: 'Password must be at least 6 characters',
        emailRequired: 'Email is required',
        invalidEmail: 'Invalid email address',
        phoneRequired: 'Phone number is required',
        invalidPhone: 'Invalid phone number',
        registrationFailed: 'Registration failed. Please try again.',
        loginFailed: 'Invalid username or password',
        logoutFailed: 'Failed to logout',
        loginSuccess: 'Login successful',
        registrationSuccess: 'Registration successful',
        logoutSuccess: 'Logout successful'
      }
    },
    home: {
      welcome: 'Welcome',
      selectServer: 'Select a server to get started',
    },
    server: {
      channels: 'Channels',
      textChannels: 'TEXT CHANNELS',
      voiceChannels: 'VOICE CHANNELS',
      createServer: 'Create a new server',
      serverName: 'Server Name',
      createChannel: 'Create a new channel',
      channelName: 'Channel Name',
      voiceChannel: 'Voice Channel',
      members: 'Members',
      join: 'Join',
      leave: 'Leave',
      invite: 'Invite Friends',
      generateInvite: 'Generate Invite Link',
      mute: 'Mute',
      unmute: 'Unmute',
      kick: 'Kick User',
      ban: 'Ban User',
      makeAdmin: 'Make Admin',
      removeAdmin: 'Remove Admin',
      volume: 'Volume',
      channelCreated: 'Channel created successfully',
      channelCreatedDesc: 'The channel has been created successfully.',
      channelError: 'Channel creation error',
      inviteSent: 'Invite sent',
      inviteSentDesc: 'The invite has been sent successfully.',
      inviteError: 'Invite error',
      selectFriend: 'Select a friend',
      sendInvite: 'Send Invite',
      channelDeleted: 'Channel deleted successfully',
      channelNameRequired: 'Channel name is required',
      error: 'Error',
      inviteFriend: 'Invite Friend',
      channelNamePlaceholder: 'Enter channel name'
    },
    settings: {
      title: 'Settings',
      language: 'Language',
      security: 'Security',
      profile: 'Profile',
      general: 'General',
      theme: {
        title: 'Theme',
        light: 'Light',
        dark: 'Dark',
        system: 'System',
      },
      audio: {
        title: 'Audio Settings',
        input: 'Input Device',
        output: 'Output Device',
        selectInput: 'Select Input Device',
        selectOutput: 'Select Output Device',
        quality: 'Audio Quality',
        selectQuality: 'Select Quality',
        qualityLow: 'Low',
        qualityMedium: 'Medium',
        qualityHigh: 'High',
        volume: 'Volume',
        testFailed: 'Test Failed',
        testFailedDesc: 'Failed to play test sound',
      },
      effects: {
        title: 'Effects',
        voice: 'Voice Effects',
        selectVoice: 'Select Voice Effect',
        voiceNone: 'None',
        voicePitchUp: 'Pitch Up',
        voicePitchDown: 'Pitch Down',
        voiceRobot: 'Robot',
        voiceEcho: 'Echo',
        noiseSuppression: 'Noise Suppression',
        selectNoiseSuppression: 'Select Noise Suppression Level',
        noiseSuppressionOff: 'Off',
        noiseSuppressionLow: 'Low',
        noiseSuppressionMedium: 'Medium',
        noiseSuppressionHigh: 'High',
      },
    },
    profile: {
      title: 'Profile Settings',
      avatarUrl: 'Avatar URL',
      bio: 'About Me',
      age: 'Age',
      saveChanges: 'Save Changes',
      updateSuccess: 'Success',
      profileUpdated: 'Your profile has been updated',
      updateError: 'Update Failed',
      viewProfile: 'View Profile',
      nickname: 'Nickname',
      status: 'Status',
      statusPlaceholder: 'What are you up to?',
      socialLinks: 'Social Links',
      discord: 'Discord',
      twitter: 'Twitter',
      instagram: 'Instagram',
      website: 'Website',
      privacy: 'Privacy Settings',
      privateProfile: 'Private Profile',
      showLastSeen: 'Show Last Seen',
      level: {
        title: 'Level',
        experience: 'Experience',
        nextLevel: 'Next Level',
        currentTitle: 'Current Title',
      },
      gifts: {
        title: 'Gifts',
        send: 'Send Gift',
        history: 'Gift History',
        received: 'Received',
        sent: 'Sent',
        selectGift: 'Select a Gift',
        message: 'Message (Optional)',
        sendGift: 'Send Gift',
        insufficientCoins: 'Insufficient coins',
        giftSent: 'Gift sent successfully',
        from: 'From',
        to: 'To',
        cost: 'Cost',
        experiencePoints: 'Experience Points',
      },
    },
    chat: {
      welcome: 'Welcome to',
      messagePlaceholder: 'Message',
      send: 'Send',
      addReaction: 'Add Reaction',
      removeReaction: 'Remove Reaction',
      reactions: 'Reactions',
      reactionAdded: 'Reaction added',
      reactionRemoved: 'Reaction removed',
    },
    coins: {
      title: 'Ozba Coins',
      balance: 'Current Balance',
      lifetimeEarned: 'Lifetime Earned',
      dailyReward: {
        title: 'Daily Reward',
        claim: 'Claim Daily Reward',
        claimed: 'Claimed',
        nextIn: 'Next reward in',
        success: 'Daily reward claimed!',
        error: 'Already claimed today',
      },
      store: {
        title: 'Coin Store',
        buyCoins: 'Buy Coins',
        popular: 'Popular',
        bonus: 'Bonus',
      },
      achievements: {
        title: 'Achievements',
        progress: 'Progress',
        completed: 'Completed',
        reward: 'Reward',
        types: {
          voice_time: 'Voice Chat Time',
          referrals: 'Referrals',
          reactions: 'Reactions',
          messages: 'Messages Sent',
        },
      },
      transaction: {
        daily_reward: 'Daily Reward',
        purchase: 'Purchase',
        achievement: 'Achievement',
        voice_activity: 'Voice Activity',
        referral: 'Referral Bonus',
      },
    },
    friends: {
      title: 'Friends',
      add: 'Add Friend',
      remove: 'Remove Friend',
      list: 'Friends',
      requests: 'Requests',
      noRequests: 'No friend requests',
      addSuccess: 'Friend Added',
      addSuccessDescription: '{username} has been added to your friends list.',
      addError: 'Could not add friend',
      removeSuccess: 'Friend Removed',
      removeSuccessDescription: '{username} has been removed from your friends list.',
      removeError: 'Could not remove friend',
      empty: 'No friends yet. Add some friends to get started!',
      searchPlaceholder: 'Enter username to add friend',
      sendMessage: 'Send Message',
      acceptSuccess: 'Friend request accepted',
      acceptError: 'Could not accept friend request',
      rejectSuccess: 'Friend request rejected',
      rejectError: 'Could not reject friend request',
    },
    blocks: {
      add: 'Block User',
      remove: 'Unblock User',
      addSuccess: 'User Blocked',
      addSuccessDescription: '{username} has been blocked.',
      addError: 'Could not block user',
      removeSuccess: 'User Unblocked',
      removeSuccessDescription: '{username} has been unblocked.',
      removeError: 'Could not unblock user',
    },
    media: {
      urlPlaceholder: 'Enter YouTube URL or music URL',
      play: 'Play',
      nowPlaying: 'Now Playing',
      queue: 'Queue',
      addedToQueue: 'Added to queue',
      skip: 'Skip',
      clearQueue: 'Clear Queue',
      errorPlayback: 'Error playing media',
      joinChannel: 'Join channel to listen',
      addMusic: 'Add Music',
      addVideo: 'Add Video',
      searchMusic: 'Search Music',
      searchVideo: 'Search Video',
      searchPlaceholder: 'Search for songs or videos...',
      searchError: 'Error searching YouTube',
    },
    voice: {
      streamError: 'Failed to access microphone',
      deviceAccessError: 'Could not access audio devices',
      testSoundError: 'Failed to play test sound',
      unmute: 'Unmute',
      mute: 'Mute',
      connecting: 'Connecting...',
      connected: 'Connected',
      disconnected: 'Disconnected',
      reconnecting: 'Reconnecting...',
      connectionError: 'Connection error occurred',
      connectionFailed: 'Connection failed',
      joinedChannel: 'Joined the channel',
      failedToJoin: 'Failed to join the channel',
      muted: 'Muted',
      unmuted: 'Unmuted',
      permissionDenied: 'Permission denied',
      microphoneAccessDenied: 'Microphone access denied',
      noMicrophoneFound: 'No microphone found',
      browserNotSupported: 'Browser not supported',
    },
    audio: {
      deviceAccessError: 'Could not access audio devices. Please check your permissions.',
      testSoundError: 'Could not play test sound',
      title: 'Audio Settings',
      inputDevice: 'Input Device',
      outputDevice: 'Output Device',
      inputVolume: 'Input Volume',
      outputVolume: 'Output Volume',
      test: 'Test Audio',
      noDevices: 'No audio devices found',
      defaultDevice: 'Default Device',
    },
    error: {
      connectionLost: 'Connection Lost',
      refreshPage: 'Please refresh the page',
      connectionError: 'Connection Error',
      tryAgainLater: 'Please try again later',
    },
  },
  tr: {
    auth: {
      login: 'Giriş Yap',
      register: 'Kayıt Ol',
      username: 'Kullanıcı Adı',
      password: 'Şifre',
      phone: 'Telefon Numarası',
      welcomeTitle: 'OZBA\'ya Hoş Geldiniz',
      welcomeDescription: 'Sesli sohbet kanalları aracılığıyla arkadaşlarınız ve topluluklarla bağlantı kurun. Kendi sunucularınızı oluşturun, sesli odalara katılın ve sohbete başlayın!',
      logout: 'Çıkış',
      loginSuccess: 'Başarıyla giriş yapıldı',
      errors: {
        usernameRequired: 'Kullanıcı adı zorunludur',
        usernameTooShort: 'Kullanıcı adı en az 3 karakter olmalıdır',
        passwordRequired: 'Şifre zorunludur',
        passwordTooShort: 'Şifre en az 6 karakter olmalıdır',
        emailRequired: 'E-posta adresi zorunludur',
        invalidEmail: 'Geçersiz e-posta adresi',
        phoneRequired: 'Telefon numarası zorunludur',
        invalidPhone: 'Geçersiz telefon numarası',
        registrationFailed: 'Kayıt işlemi başarısız oldu. Lütfen tekrar deneyin.',
        loginFailed: 'Geçersiz kullanıcı adı veya şifre',
        logoutFailed: 'Çıkış yapılamadı',
        loginSuccess: 'Giriş başarılı',
        registrationSuccess: 'Kayıt başarılı',
        logoutSuccess: 'Çıkış başarılı'
      }
    },
    home: {
      welcome: 'Hoş Geldiniz',
      selectServer: 'Başlamak için bir sunucu seçin',
    },
    server: {
      channels: 'Kanallar',
      textChannels: 'METİN KANALLARI',
      voiceChannels: 'SESLİ KANALLAR',
      createServer: 'Yeni sunucu oluştur',
      serverName: 'Sunucu Adı',
      createChannel: 'Yeni kanal oluştur',
      channelName: 'Kanal Adı',
      voiceChannel: 'Sesli Kanal',
      members: 'Üyeler',
      join: 'Katıl',
      leave: 'Ayrıl',
      invite: 'Arkadaşlarını Davet Et',
      generateInvite: 'Davet Linki Oluştur',
      mute: 'Sustur',
      unmute: 'Susturmayı Kaldır',
      kick: 'Kullanıcıyı At',
      ban: 'Kullanıcıyı Yasakla',
      makeAdmin: 'Admin Yap',
      removeAdmin: 'Admin Yetkisini Kaldır',
      volume: 'Ses Seviyesi',
      channelCreated: 'Kanal başarıyla oluşturuldu',
      channelCreatedDesc: 'Kanal başarıyla oluşturuldu.',
      channelError: 'Kanal oluşturma hatası',
      inviteSent: 'Davet gönderildi',
      inviteSentDesc: 'Davet başarıyla gönderildi.',
      inviteError: 'Davet hatası',
      selectFriend: 'Bir arkadaş seçin',
      sendInvite: 'Davet Gönder',
      channelDeleted: 'Kanal başarıyla silindi',
      channelNameRequired: 'Kanal adı zorunludur',
      error: 'Hata',
      inviteFriend: 'Arkadaş Davet Et',
      channelNamePlaceholder: 'Kanal adını girin'
    },
    settings: {
      title: 'Ayarlar',
      language: 'Dil',
      security: 'Güvenlik',
      profile: 'Profil',
      general: 'Genel',
      theme: {
        title: 'Tema',
        light: 'Açık',
        dark: 'Koyu',
        system: 'Sistem',
      },
      audio: {
        title: 'Ses Ayarları',
        input: 'Giriş Cihazı',
        output: 'Çıkış Cihazı',
        selectInput: 'Giriş Cihazını Seç',
        selectOutput: 'Çıkış Cihazını Seç',
        quality: 'Ses Kalitesi',
        selectQuality: 'Kaliteyi Seç',
        qualityLow: 'Düşük',
        qualityMedium: 'Orta',
        qualityHigh: 'Yüksek',
        volume: 'Ses Seviyesi',
        testFailed: 'Test Başarısız',
        testFailedDesc: 'Test sesi çalınamadı',
      },
      effects: {
        title: 'Efektler',
        voice: 'Ses Efektleri',
        selectVoice: 'Ses Efektini Seç',
        voiceNone: 'Yok',
        voicePitchUp: 'Ses Yükselt',
        voicePitchDown: 'Ses Alçalt',
        voiceRobot: 'Robot',
        voiceEcho: 'Eko',
        noiseSuppression: 'Gürültü Engelleme',
        selectNoiseSuppression: 'Gürültü Engelleme Seviyesini Seç',
        noiseSuppressionOff: 'Kapalı',
        noiseSuppressionLow: 'Düşük',
        noiseSuppressionMedium: 'Orta',
        noiseSuppressionHigh: 'Yüksek',
      },
    },
    profile: {
      title: 'Profil Ayarları',
      avatarUrl: 'Profil Fotoğrafı URL',
      bio: 'Hakkımda',
      age: 'Yaş',
      saveChanges: 'Değişiklikleri Kaydet',
      updateSuccess: 'Başarılı',
      profileUpdated: 'Profiliniz güncellendi',
      updateError: 'Güncelleme Başarısız',
      viewProfile: 'Profili Görüntüle',
      nickname: 'Takma Ad',
      status: 'Durum',
      statusPlaceholder: 'Ne yapıyorsun?',
      socialLinks: 'Sosyal Medya Bağlantıları',
      discord: 'Discord',
      twitter: 'Twitter',
      instagram: 'Instagram',
      website: 'Web Sitesi',
      privacy: 'Gizlilik Ayarları',
      privateProfile: 'Özel Profil',
      showLastSeen: 'Son Görülme Göster',
      level: {
        title: 'Seviye',
        experience: 'Deneyim',
        nextLevel: 'Sonraki Seviye',
        currentTitle: 'Mevcut Ünvan',
      },
      gifts: {
        title: 'Hediyeler',
        send: 'Hediye Gönder',
        history: 'Hediye Geçmişi',
        received: 'Alınan',
        sent: 'Gönderilen',
        selectGift: 'Hediye Seç',
        message: 'Mesaj (İsteğe Bağlı)',
        sendGift: 'Hediye Gönder',
        insufficientCoins: 'Yetersiz coin',
        giftSent: 'Hediye başarıyla gönderildi',
        from: 'Gönderen',
        to: 'Alan',
        cost: 'Fiyat',
        experiencePoints: 'Deneyim Puanı',
      },
    },
    chat: {
      welcome: 'Hoş geldiniz',
      messagePlaceholder: 'Mesaj',
      send: 'Gönder',
      addReaction: 'Tepki Ekle',
      removeReaction: 'Tepkiyi Kaldır',
      reactions: 'Tepkiler',
      reactionAdded: 'Tepki eklendi',
      reactionRemoved: 'Tepki kaldırıldı',
    },
    coins: {
      title: 'Ozba Coin',
      balance: 'Mevcut Bakiye',
      lifetimeEarned: 'Toplam Kazanılan',
      dailyReward: {
        title: 'Günlük Ödül',
        claim: 'Günlük Ödülü Al',
        claimed: 'Alındı',
        nextIn: 'Sonraki ödül',
        success: 'Günlük ödül alındı!',
        error: 'Bugün zaten alındı',
      },
      store: {
        title: 'Coin Mağazası',
        buyCoins: 'Coin Satın Al',
        popular: 'Popüler',
        bonus: 'Bonus',
      },
      achievements: {
        title: 'Başarılar',
        progress: 'İlerleme',
        completed: 'Tamamlandı',
        reward: 'Ödül',
        types: {
          voice_time: 'Sesli Sohbet Süresi',
          referrals: 'Davetler',
          reactions: 'Tepkiler',
          messages: 'Gönderilen Mesajlar',
        },
      },
      transaction: {
        daily_reward: 'Günlük Ödül',
        purchase: 'Satın Alma',
        achievement: 'Başarı',
        voice_activity: 'Sesli Aktivite',
        referral: 'Davet Bonusu',
      },
    },
    friends: {
      title: 'Arkadaşlarım',
      add: 'Arkadaş Ekle',
      remove: 'Arkadaşı Sil',
      list: 'Arkadaşlar',
      requests: 'İstekler',
      noRequests: 'Arkadaşlık isteği yok',
      addSuccess: 'Arkadaş Eklendi',
      addSuccessDescription: '{username} arkadaş listenize eklendi.',
      addError: 'Arkadaş eklenemedi',
      removeSuccess: 'Arkadaş Silindi',
      removeSuccessDescription: '{username} arkadaş listenizden silindi.',
      removeError: 'Arkadaş silinemedi',
      empty: 'Henüz arkadaşınız yok. Arkadaş ekleyerek başlayın!',
      searchPlaceholder: 'Arkadaş eklemek için kullanıcı adı girin',
      sendMessage: 'Mesaj Gönder',
      newRequest: 'Yeni Arkadaşlık İsteği',
      requestReceived: '{username} size arkadaşlık isteği gönderdi',
      requestAccepted: 'Arkadaşlık İsteği Kabul Edildi',
      nowFriends: '{username} ile artık arkadaşsınız',
      requestRejected: 'Arkadaşlık İsteği Reddedildi',
      requestRejectedDesc: '{username} arkadaşlık isteğinizi reddetti',
      removed: 'Arkadaşlıktan Çıkarıldı',
      removedDesc: '{username} sizi arkadaşlıktan çıkardı',
      requestSent: 'Arkadaşlık İsteği Gönderildi',
      requestSentDescription: 'Arkadaşlık isteğiniz başarıyla gönderildi',
      requestError: 'İstek Gönderme Hatası',
      acceptError: 'Kabul Etme Hatası',
      rejectError: 'Reddetme Hatası',
      addFriend: 'Arkadaş Ekle',
      removeFriend: 'Arkadaşı Sil',
      pending: 'İstek Beklemede',
      accept: 'Kabul Et',
      reject: 'Reddet'
    },
    blocks: {
      add: 'Engelle',
      remove: 'Engeli Kaldır',
      addSuccess: 'Kullanıcı Engellendi',
      addSuccessDescription: '{username} engellendi.',
      addError: 'Kullanıcı engellenemedi',
      removeSuccess: 'Engel Kaldırıldı',
      removeSuccessDescription: '{username} engellemesi kaldırıldı.',
      removeError: 'Engel kaldırılamadı',
    },
    media: {
      urlPlaceholder: 'YouTube URL veya müzik URL\'si girin',
      play: 'Oynat',
      nowPlaying: 'Şimdi Çalıyor',
      queue: 'Sıradakiler',
      addedToQueue: 'Sıraya eklendi',
      skip: 'Geç',
      clearQueue: 'Sırayı Temizle',
      errorPlayback: 'Medya oynatma hatası',
      joinChannel: 'Dinlemek için kanala katılın',
      addMusic: 'Müzik Ekle',
      addVideo: 'Video Ekle',
      searchMusic: 'Müzik Ara',
      searchVideo: 'Video Ara',
      searchPlaceholder: 'Şarkı veya video ara...',
      searchError: 'YouTube araması sırasında hata oluştu',
    },
    voice: {
      streamError: 'Mikrofona erişilemedi',
      deviceAccessError: 'Ses cihazlarına erişilemedi',
      testSoundError: 'Test sesi çalınamadı',
      unmute: 'Sesi Aç',
      mute: 'Sesi Kapat',
      connecting: 'Bağlanıyor...',
      connected: 'Bağlandı',
      disconnected: 'Bağlantı kesildi',
      reconnecting: 'Yeniden bağlanıyor...',
      connectionError: 'Bağlantı hatası oluştu',
      connectionFailed: 'Bağlantı başarısız',
    },
    audio: {
      deviceAccessError: 'Ses cihazlarına erişilemedi. Lütfen izinleri kontrol edin.',
      testSoundError: 'Test sesi çalınamadı',
      title: 'Ses Ayarları',
      inputDevice: 'Giriş Cihazı',
      outputDevice: 'Çıkış Cihazı',
      inputVolume: 'Giriş Ses Seviyesi',
      outputVolume: 'Çıkış Ses Seviyesi',
      test: 'Ses Testi',
      noDevices: 'Ses cihazı bulunamadı',
      defaultDevice: 'Varsayılan Cihaz',
    },
    error: {
      connectionLost: 'Bağlantı Kesildi',
      refreshPage: 'Lütfen sayfayı yenileyin',
      connectionError: 'Bağlantı Hatası',
      tryAgainLater: 'Lütfen daha sonra tekrar deneyin'
    }
  }
};